### ISSUE TITLE
GitHub repository link

### ISSUE THREAD

**Issue by Ayaan2907** [ats1999/time-stamp#17]
Need a button for accessing the code of the app.

**Comment by ats1999** [comment]
Thanks for the PR

**Comment by ats1999** [comment]
![1645791491103](https://user-images.githubusercontent.com/54087826/155714136-69e60597-9ae7-4738-a6a2-f4f8c6beeb68.jpg)

**Comment by ats1999** [comment]
![aer](https://user-images.githubusercontent.com/54087826/155735998-f820c513-c218-495e-97ed-be823f83aaf5.jpg)

**Comment by ats1999** [comment]
![Untitled Diagram drawio](https://user-images.githubusercontent.com/54087826/159131575-289e8636-cace-4663-9e5d-53667499986a.png)

**Comment by ats1999** [comment]
![final](https://user-images.githubusercontent.com/54087826/159132195-1e609a9d-2215-4a2b-97ec-6527fd5afe26.svg)

**Comment by ats1999** [comment]
![Untitled Diagram drawio](https://user-images.githubusercontent.com/54087826/162647607-3786bb1b-e122-4903-8476-1004e6855a59.svg)

**Comment by ats1999** [comment]
![transparent](https://user-images.githubusercontent.com/54087826/162647703-655b1882-fc16-4e16-80f0-262e728382b7.svg)

**Comment by Ayaan2907** [comment]
Hey man what are you putting here in this communication

**Comment by Ayaan2907** [comment]
I think its not much relevant to this #issue

**Comment by ats1999** [comment]
By mistake added to other repo
